"""
backend/agents/memory.py
=========================
Session-scoped conversation memory for the AI Teaching Assistant.

Stores recent Q&A exchanges per session so students can ask follow-up
questions naturally (e.g., "What about its time complexity?" refers to
the algorithm discussed in the previous question).

Design decisions
----------------
- **In-memory dict**: No database needed. Sessions are transient.
- **Auto-expiry**: Sessions expire after 30 minutes of inactivity.
- **Bounded**: Max 5 exchanges per session to control token usage.
- **Thread-safe**: Uses a lock for concurrent request safety.
"""

import logging
import threading
import time
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
MAX_HISTORY_PER_SESSION = 5     # Maximum Q&A pairs to remember
SESSION_TTL_SECONDS = 1800      # 30 minutes
CLEANUP_INTERVAL_SECONDS = 300  # Run cleanup every 5 minutes


# ---------------------------------------------------------------------------
# SessionMemory
# ---------------------------------------------------------------------------

class SessionMemory:
    """
    In-memory session store for conversation history.

    Each session stores a bounded list of Q&A exchanges with timestamps.
    Sessions auto-expire after ``SESSION_TTL_SECONDS`` of inactivity.
    """

    def __init__(
        self,
        max_history: int = MAX_HISTORY_PER_SESSION,
        ttl_seconds: int = SESSION_TTL_SECONDS,
    ) -> None:
        self.max_history = max_history
        self.ttl_seconds = ttl_seconds
        self._sessions: Dict[str, Dict[str, Any]] = {}
        self._lock = threading.Lock()
        self._last_cleanup = time.time()

    # -----------------------------------------------------------------
    # Public API
    # -----------------------------------------------------------------

    def add_exchange(
        self,
        session_id: str,
        question: str,
        answer_summary: str,
        topic: str = "",
    ) -> None:
        """
        Record a Q&A exchange in the session.

        Parameters
        ----------
        session_id : str
            Unique session identifier (generated by frontend).
        question : str
            The student's question.
        answer_summary : str
            A truncated summary of the answer (first ~200 chars).
        topic : str, optional
            The topic of the exchange.
        """
        with self._lock:
            self._maybe_cleanup()

            if session_id not in self._sessions:
                self._sessions[session_id] = {
                    "history": [],
                    "last_active": time.time(),
                }

            session = self._sessions[session_id]
            session["last_active"] = time.time()
            session["history"].append({
                "question": question,
                "answer_summary": answer_summary[:200],
                "topic": topic,
                "timestamp": time.time(),
            })

            # Trim to max history
            if len(session["history"]) > self.max_history:
                session["history"] = session["history"][-self.max_history:]

            logger.debug(
                "Session %s: recorded exchange (total: %d)",
                session_id[:12],
                len(session["history"]),
            )

    def get_history(self, session_id: str) -> List[Dict]:
        """
        Return the conversation history for a session.

        Returns
        -------
        list[dict]
            Each dict has ``question``, ``answer_summary``, ``topic``,
            and ``timestamp`` keys. Empty list if session not found.
        """
        with self._lock:
            session = self._sessions.get(session_id)
            if session is None:
                return []

            # Touch the session to prevent expiry
            session["last_active"] = time.time()
            return list(session["history"])

    def get_context_summary(self, session_id: str) -> str:
        """
        Build a text summary of recent conversation for the query rewriter.

        Returns
        -------
        str
            A formatted string of recent Q&A pairs, or empty string.
        """
        history = self.get_history(session_id)
        if not history:
            return ""

        lines = []
        for h in history[-3:]:  # Last 3 exchanges
            lines.append(f"Q: {h['question']}")
            if h.get("answer_summary"):
                lines.append(f"A: {h['answer_summary']}")
        return "\n".join(lines)

    def get_session_count(self) -> int:
        """Return the number of active sessions."""
        with self._lock:
            return len(self._sessions)

    def clear(self, session_id: Optional[str] = None) -> None:
        """Clear a specific session or all conversation memory sessions."""
        with self._lock:
            if session_id:
                self._sessions.pop(session_id, None)
            else:
                self._sessions.clear()
        logger.info("Session memory cleared.")


    # -----------------------------------------------------------------
    # Internal
    # -----------------------------------------------------------------

    def _maybe_cleanup(self) -> None:
        """Remove expired sessions periodically."""
        now = time.time()
        if now - self._last_cleanup < CLEANUP_INTERVAL_SECONDS:
            return

        self._last_cleanup = now
        expired = [
            sid
            for sid, data in self._sessions.items()
            if now - data["last_active"] > self.ttl_seconds
        ]

        for sid in expired:
            del self._sessions[sid]

        if expired:
            logger.info("Cleaned up %d expired sessions.", len(expired))


# ---------------------------------------------------------------------------
# Module-level singleton
# ---------------------------------------------------------------------------
_memory_singleton: Optional[SessionMemory] = None
_memory_lock = threading.Lock()


def get_memory() -> SessionMemory:
    """Return the shared SessionMemory singleton."""
    global _memory_singleton
    with _memory_lock:
        if _memory_singleton is None:
            _memory_singleton = SessionMemory()
        return _memory_singleton
